In [1]:
import json
import pandas as pd
import numpy as np

In [2]:
file_dir = 'C://Users/revip/Week 8 ETL/'

In [4]:
f'{file_dir}wikipedia-movies.json'

'C://Users/revip/Week 8 ETL/wikipedia-movies.json'

In [5]:
with open(f'{file_dir}/wikipedia-movies.json', mode='r') as file:
    wiki_movies_raw = json.load(file)

In [6]:
len(wiki_movies_raw)

7311

In [7]:
# First 5 records
wiki_movies_raw[:5]

[{'url': 'https://en.wikipedia.org/wiki/The_Adventures_of_Ford_Fairlane',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0098987/',
  'title': 'The Adventures of Ford Fairlane',
  'Directed by': 'Renny Harlin',
  'Produced by': ['Steve Perry', 'Joel Silver'],
  'Screenplay by': ['David Arnott', 'James Cappe', 'Daniel Waters'],
  'Story by': ['David Arnott', 'James Cappe'],
  'Based on': ['Characters', 'by Rex Weiner'],
  'Starring': ['Andrew Dice Clay',
   'Wayne Newton',
   'Priscilla Presley',
   'Lauren Holly',
   'Morris Day',
   'Robert Englund',
   "Ed O'Neill"],
  'Narrated by': 'Andrew "Dice" Clay',
  'Music by': ['Cliff Eidelman', 'Yello'],
  'Cinematography': 'Oliver Wood',
  'Edited by': 'Michael Tronick',
  'Productioncompany ': 'Silver Pictures',
  'Distributed by': '20th Century Fox',
  'Release date': ['July 11, 1990', '(', '1990-07-11', ')'],
  'Running time': '102 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$20 million',
  'Box office': '$21.4 million'},
 {'url': 'https://en.wikipedia.org/wiki/After_Dark,_My_Sweet',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0098994/',
  'title': 'After Dark, My Sweet',
  'Directed by': 'James Foley',
  'Produced by': ['Ric Kidney', 'Robert Redlin'],
  'Screenplay by': ['James Foley', 'Robert Redlin'],
  'Based on': ['the novel', 'After Dark, My Sweet', 'by', 'Jim Thompson'],
  'Starring': ['Jason Patric',
   'Rachel Ward',
   'Bruce Dern',
   'George Dickerson'],
  'Music by': 'Maurice Jarre',
  'Cinematography': 'Mark Plummer',
  'Edited by': 'Howard E. Smith',
  'Productioncompany ': 'Avenue Pictures',
  'Distributed by': 'Avenue Pictures',
  'Release date': ['May 17, 1990',
   '(',
   '1990-05-17',
   ')',
   '(Cannes Film Market)',
   'August 24, 1990',
   '(',
   '1990-08-24',
   ')',
   '(United States)'],
  'Running time': '114 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$6 million',
  'Box office': '$2.7 million'},
 {'url': 'https://en.wikipedia.org/wiki/Air_America_(film)',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0099005/',
  'title': 'Air America',
  'Directed by': 'Roger Spottiswoode',
  'Produced by': 'Daniel Melnick',
  'Screenplay by': ['John Eskow', 'Richard Rush'],
  'Based on': ['Air America', 'by', 'Christopher Robbins'],
  'Starring': ['Mel Gibson',
   'Robert Downey Jr.',
   'Nancy Travis',
   'David Marshall Grant',
   'Lane Smith'],
  'Music by': 'Charles Gross',
  'Cinematography': 'Roger Deakins',
  'Edited by': ['John Bloom', 'Lois Freeman-Fox'],
  'Productioncompany ': ['Carolco Pictures', 'IndieProd Company'],
  'Distributed by': 'TriStar Pictures',
  'Release date': ['August 10, 1990', '(', '1990-08-10', ')'],
  'Running time': '113 minutes',
  'Country': 'United States',
  'Language': ['English', 'Lao'],
  'Budget': '$35 million',
  'Box office': '$57,718,089'},
 {'url': 'https://en.wikipedia.org/wiki/Alice_(1990_film)',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0099012/',
  'title': 'Alice',
  'Directed by': 'Woody Allen',
  'Produced by': 'Robert Greenhut',
  'Written by': 'Woody Allen',
  'Starring': ['Alec Baldwin',
   'Blythe Danner',
   'Judy Davis',
   'Mia Farrow',
   'William Hurt',
   'Keye Luke',
   'Joe Mantegna',
   'Bernadette Peters'],
  'Cinematography': 'Carlo Di Palma',
  'Edited by': 'Susan E. Morse',
  'Distributed by': 'Orion Pictures',
  'Release date': ['December 25, 1990', '(', '1990-12-25', ')'],
  'Running time': '106 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$12 million',
  'Box office': '$7,331,647'},
 {'url': 'https://en.wikipedia.org/wiki/Almost_an_Angel',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0099018/',
  'title': 'Almost an Angel',
  'Directed by': 'John Cornell',
  'Produced by': 'John Cornell',
  'Written by': 'Paul Hogan',
  'Starring': ['Paul Hogan', 'Elias Koteas', 'Linda Kozlowski'],
  'Music by': 'Maurice Jarre',
  'Cinematography': 'Russell Boyd',
  'Edited by': 'David Stiven',
  'Distributed by': 'Paramount Pictures',
  'Release date': 'December 19, 1990',
  'Running time': '95 minutes',
  'Country': 'US',
  'Language': 'English',
  'Budget': '$25 million',
  'Box office': '$6,939,946 (USA)'}]

In [8]:
# Last 5 records
wiki_movies_raw[-5:]

[{'url': 'https://en.wikipedia.org/wiki/Holmes_%26_Watson',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt1255919/',
  'title': 'Holmes & Watson',
  'Directed by': 'Etan Cohen',
  'Produced by': ['Will Ferrell',
   'Adam McKay',
   'Jimmy Miller',
   'Clayton Townsend'],
  'Screenplay by': 'Etan Cohen',
  'Based on': ['Sherlock Holmes',
   'and',
   'Dr. Watson',
   'by',
   'Sir Arthur Conan Doyle'],
  'Starring': ['Will Ferrell',
   'John C. Reilly',
   'Rebecca Hall',
   'Rob Brydon',
   'Steve Coogan',
   'Ralph Fiennes'],
  'Music by': 'Mark Mothersbaugh',
  'Cinematography': 'Oliver Wood',
  'Edited by': 'Dean Zimmerman',
  'Productioncompanies ': ['Columbia Pictures',
   'Gary Sanchez Productions',
   'Mosaic Media Group',
   'Mimran Schur Pictures'],
  'Distributed by': 'Sony Pictures Releasing',
  'Release date': ['December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '90 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$42 million',
  'Box office': '$41.9 million'},
 {'url': 'https://en.wikipedia.org/wiki/Vice_(2018_film)',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt6266538/',
  'title': 'Vice',
  'Directed by': 'Adam McKay',
  'Produced by': ['Brad Pitt',
   'Dede Gardner',
   'Jeremy Kleiner',
   'Kevin J. Messick',
   'Will Ferrell',
   'Adam McKay'],
  'Written by': 'Adam McKay',
  'Starring': ['Christian Bale',
   'Amy Adams',
   'Steve Carell',
   'Sam Rockwell',
   'Tyler Perry',
   'Alison Pill',
   'Lily Rabe',
   'Jesse Plemons'],
  'Music by': 'Nicholas Britell',
  'Cinematography': 'Greig Fraser',
  'Edited by': 'Hank Corwin',
  'Productioncompany ': ['Plan B Entertainment',
   'Gary Sanchez Productions',
   'Annapurna Pictures'],
  'Distributed by': 'Mirror Releasing',
  'Release date': ['December 11, 2018',
   '(',
   '2018-12-11',
   ')',
   '(',
   'Samuel Goldwyn Theater',
   ')',
   'December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '132 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$60 million',
  'Box office': '$76.1 million'},
 {'url': 'https://en.wikipedia.org/wiki/On_the_Basis_of_Sex',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt4669788/',
  'title': 'On the Basis of Sex',
  'Directed by': 'Mimi Leder',
  'Produced by': 'Robert W. Cort',
  'Written by': 'Daniel Stiepleman',
  'Starring': ['Felicity Jones',
   'Armie Hammer',
   'Justin Theroux',
   'Sam Waterston',
   'Kathy Bates'],
  'Music by': 'Mychael Danna',
  'Cinematography': 'Michael Grady',
  'Edited by': 'Michelle Tesoro',
  'Productioncompanies ': ['Focus Features',
   '[1]',
   'Participant Media',
   '[1]',
   'Robert Cort Productions',
   '[1]',
   'Alibaba Pictures',
   '[2]'],
  'Distributed by': 'Focus Features',
  'Release date': ['November 8, 2018',
   '(',
   '2018-11-08',
   ')',
   '(',
   'AFI Fest',
   ')',
   'December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '120 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$20 million',
  'Box office': '$38.4 million'},
 {'url': 'https://en.wikipedia.org/wiki/Destroyer_(2018_film)',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt7137380/',
  'title': 'Destroyer',
  'Directed by': 'Karyn Kusama',
  'Produced by': ['Fred Berger', 'Phil Hay', 'Matt Manfredi'],
  'Written by': ['Phil Hay', 'Matt Manfredi'],
  'Starring': ['Nicole Kidman',
   'Sebastian Stan',
   'Toby Kebbell',
   'Tatiana Maslany',
   'Bradley Whitford',
   'Jade Pettyjohn',
   'Scoot McNairy'],
  'Music by': 'Theodore Shapiro',
  'Cinematography': 'Julie Kirkwood',
  'Edited by': 'Plummy Tucker',
  'Productioncompany ': ['30West',
   'Automatik Entertainment',
   'Annapurna Pictures'],
  'Distributed by': 'Mirror Releasing',
  'Release date': ['August 31, 2018',
   '(',
   '2018-08-31',
   ')',
   '(',
   'Telluride',
   ')',
   'December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '123 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$9 million',
  'Box office': '$5.5 million'},
 {'url': 'https://en.wikipedia.org/wiki/Black_Mirror:_Bandersnatch',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt9495224/',
  'title': 'Bandersnatch',
  'Directed by': 'David Slade',
  'Produced by': 'Russell McLean',
  'Written by': 'Charlie Brooker',
  'Starring': ['Fionn Whitehead',
   'Will Poulter',
   'Craig Parkinson',
   'Alice Lowe',
   'Asim Chaudhry'],
  'Music by': 'Brian Reitzell',
  'Cinematography': ['Aaron Morton', 'Jake Polonsky'],
  'Edited by': 'Tony Kearns',
  'Productioncompany ': ['House of Tomorrow', 'Netflix'],
  'Distributed by': 'Netflix',
  'Release date': ['28 December 2018', '(', '2018-12-28', ')'],
  'Running time': 'Variable; 90 minutes for default path',
  'Country': 'United Kingdom',
  'Language': 'English'}]

In [9]:
# Some records in the middle
wiki_movies_raw[3600:3605]

[{'url': 'https://en.wikipedia.org/wiki/Benji:_Off_the_Leash!',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0315273/',
  'title': 'Benji: Off the Leash!',
  'Directed by': 'Joe Camp',
  'Written by': 'Joe Camp',
  'Starring': ['Benji', 'Nick Whitaker', 'Shaggy', 'Gypsy the Cockatoo'],
  'Music by': 'Antonio di Lorenzo',
  'Productioncompany ': 'Mulberry Square Productions',
  'Distributed by': 'Mulberry Square Productions',
  'Release date': ['March 26, 2004', '(', '2004-03-26', ')'],
  'Running time': '97 min',
  'Country': 'United States',
  'Language': 'English',
  'Box office': '$3,817,362'},
 {'url': 'https://en.wikipedia.org/wiki/The_Best_Thief_in_the_World',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0389796/',
  'title': 'The Best Thief in the World',
  'Directed by': 'Jacob Kornbluth',
  'Produced by': ['Tim Perrell', 'Nicola Usborne'],
  'Written by': 'Jacob Kornbluth',
  'Starring': ['Marc Rozendaal',
   'Michael Silverman',
   'David Warshofsky',
   'Audra McDonald',
   'Lois Smith'],
  'Music by': ['Prince Paul', 'and', 'Don Newkirk'],
  'Cinematography': 'Ben Kutchins',
  'Edited by': 'Stephanie Sterner',
  'Distributed by': 'Showtime Networks',
  'Release date': ['January 16, 2004', '(', '2004-01-16', ')'],
  'Running time': '93 minutes',
  'Country': 'United States',
  'Language': 'English'},
 {'url': 'https://en.wikipedia.org/wiki/Beyond_the_Sea_(2004_film)',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0363473/',
  'title': 'Beyond the Sea',
  'Directed by': 'Kevin Spacey',
  'Produced by': ['Kevin Spacey',
   'Phillip Barry',
   'Dana Brunetti',
   'Arthur Friedman',
   'Jan Fantl',
   'Andy Paterson'],
  'Written by': ['Lewis Colick', 'Kevin Spacey'],
  'Starring': ['Kevin Spacey', 'Kate Bosworth', 'Bob Hoskins', 'John Goodman'],
  'Music by': 'Bobby Darin',
  'Cinematography': 'Eduardo Serra',
  'Edited by': 'Trevor Waite',
  'Productioncompany ': 'Trigger Street Productions',
  'Distributed by': ['Lionsgate Films',
   '(USA)',
   'Entertainment Film Distributors',
   '(UK)',
   'GAGA',
   '(Japan)',
   'Maple Pictures',
   '(Canada)'],
  'Release date': ['December 17, 2004', '(', '2004-12-17', ')'],
  'Running time': '118 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$25 million',
  'Box office': '$8.4 million'},
 {'url': 'https://en.wikipedia.org/wiki/The_Big_Bounce_(2004_film)',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0315824/',
  'title': 'The Big Bounce',
  'Directed by': 'George Armitage',
  'Produced by': ['George Armitage', 'Steve Bing'],
  'Screenplay by': 'Sebastian Gutierrez',
  'Based on': ['The Big Bounce', 'by', 'Elmore Leonard'],
  'Starring': ['Owen Wilson',
   'Charlie Sheen',
   'Morgan Freeman',
   'Sara Foster',
   'Gary Sinise'],
  'Music by': 'George S. Clinton',
  'Cinematography': 'Jeffrey L. Kimball',
  'Edited by': 'Barry Malkin',
  'Productioncompany ': 'Shangri-La Entertainment',
  'Distributed by': 'Warner Bros. Pictures',
  'Release date': ['January 30, 2004', '(', '2004-01-30', ')'],
  'Running time': '88 minutes',
  'Language': 'English',
  'Budget': '$50 million',
  'Box office': '$6.8 million'},
 {'url': 'https://en.wikipedia.org/wiki/Birth_(film)',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0337876/',
  'title': 'Birth',
  'Directed by': 'Jonathan Glazer',
  'Produced by': ['Lizie Gower', 'Nick Morris', 'Jean-Louis Piel'],
  'Written by': ['Jean-Claude Carrière', 'Milo Addica', 'Jonathan Glazer'],
  'Starring': ['Nicole Kidman',
   'Cameron Bright',
   'Danny Huston',
   'Lauren Bacall'],
  'Music by': 'Alexandre Desplat',
  'Cinematography': 'Harris Savides',
  'Edited by': ['Sam Sneade', 'Claus Wehlisch'],
  'Distributed by': 'New Line Cinema',
  'Release date': ['November 8, 2004', '(', '2004-11-08', ')'],
  'Running time': '96 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$20 million',
  'Box office': '$23.9 million'}]

In [10]:
kaggle_metadata = pd.read_csv(f'{file_dir}movies_metadata.csv', low_memory=False)
ratings = pd.read_csv(f'{file_dir}ratings.csv')

In [12]:
kaggle_metadata.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [13]:
kaggle_metadata.tail()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [14]:
kaggle_metadata.sample()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
1603,False,"{'id': 9818, 'name': 'Mortal Kombat Collection...",30000000,"[{'id': 28, 'name': 'Action'}, {'id': 14, 'nam...",NaN,9823,tt0119707,en,Mortal Kombat: Annihilation,A group of heroic warriors has only six days t...,...,1997-11-21,51376861.0,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"The world was created in six days, so too shal...",Mortal Kombat: Annihilation,False,3.8,225.0

In [15]:
ratings.head()

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [16]:
ratings.tail()

          userId  movieId  rating   timestamp
26024284  270896    58559     5.0  1257031564
26024285  270896    60069     5.0  1257032032
26024286  270896    63082     4.5  1257031764
26024287  270896    64957     4.5  1257033990
26024288  270896    71878     2.0  1257031858

In [18]:
ratings.sample(n=6)

          userId  movieId  rating   timestamp
855658      8692     2571     3.0  1090411073
15349873  159770     1035     4.0  1105980786
3187675    33169      899     4.0   947207735
492046      5089     2662     4.0   943646586
2120781    22016       47     5.0   844354080
22925147  238093    34405     3.5  1335535215

In [19]:
wiki_movies_df = pd.DataFrame(wiki_movies_raw)

In [20]:
wiki_movies_df.head()

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990.0,https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,Renny Harlin,"[Steve Perry, Joel Silver]","[David Arnott, James Cappe, Daniel Waters]","[David Arnott, James Cappe]","[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990.0,https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet",James Foley,"[Ric Kidney, Robert Redlin]","[James Foley, Robert Redlin]",NaN,"[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://en.wikipedia.org/wiki/Air_America_(film),1990.0,https://www.imdb.com/title/tt0099005/,Air America,Roger Spottiswoode,Daniel Melnick,"[John Eskow, Richard Rush]",NaN,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990.0,https://www.imdb.com/title/tt0099012/,Alice,Woody Allen,Robert Greenhut,NaN,NaN,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990.0,https://www.imdb.com/title/tt0099018/,Almost an Angel,John Cornell,John Cornell,NaN,NaN,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
wiki_movies_df.columns.tolist()

['url',
 'year',
 'imdb_link',
 'title',
 'Directed by',
 'Produced by',
 'Screenplay by',
 'Story by',
 'Based on',
 'Starring',
 'Narrated by',
 'Music by',
 'Cinematography',
 'Edited by',
 'Productioncompany ',
 'Distributed by',
 'Release date',
 'Running time',
 'Country',
 'Language',
 'Budget',
 'Box office',
 'Written by',
 'Genre',
 'Theme music composer',
 'Country of origin',
 'Original language(s)',
 'Producer(s)',
 'Editor(s)',
 'Production company(s)',
 'Original network',
 'Original release',
 'Productioncompanies ',
 'Executive producer(s)',
 'Production location(s)',
 'Distributor',
 'Picture format',
 'Audio format',
 'Voices of',
 'Followed by',
 'Composer(s)',
 'Created by',
 'Also known as',
 'Opening theme',
 'No. of episodes',
 'Preceded by',
 'Author',
 'Publisher',
 'Publication date',
 'Media type',
 'Pages',
 'ISBN',
 'OCLC',
 'LC Class',
 'Cover artist',
 'Series',
 'Set in',
 'Adaptation by',
 'Suggested by',
 'Biographical data',
 'Born',
 'Died',
 'Resting place',
 'Occupation',
 'Years active',
 'Spouse(s)',
 'Children',
 'Parent(s)',
 'Genres',
 'Instruments',
 'Labels',
 'Website',
 'Traditional',
 'Mandarin',
 'Type',
 'Industry',
 'Fate',
 'Founded',
 'Founder',
 'Headquarters',
 'Parent',
 'Released',
 'Recorded',
 'Venue',
 'Length',
 'Label',
 'Director',
 'Producer',
 'Area',
 'Coordinates',
 'Status',
 'Opening date',
 'Closing date',
 'Replaced',
 'Replaced by',
 'Name',
 'Attraction type',
 'Music',
 'Duration',
 'Simplified Chinese',
 'Traditional Chinese',
 'Hanyu Pinyin',
 'Literal meaning',
 'Transcriptions',
 'Bopomofo',
 'Gwoyeu Romatzyh',
 'Wade–Giles',
 'IPA',
 'Yale Romanization',
 'Jyutping',
 'Hokkien POJ',
 'Animation by',
 'Color process',
 'Engine(s)',
 'Genre(s)',
 'Actor control',
 'Production company',
 'Release(s)',
 'Format(s)',
 'Simplified',
 'Characters',
 'Date premiered',
 'Place premiered',
 'Setting',
 'Original language',
 'Subject',
 'Published',
 'Dewey Decimal',
 'Text',
 'Illustrator',
 'Original title',
 'Published in English',
 'French',
 'Developed by',
 'Ending theme',
 'No. of seasons',
 'Nationality',
 'Portrayed by',
 'Alias',
 'Species',
 'Gender',
 'Family',
 'Alma mater',
 'Camera setup',
 'Novel(s)',
 'Comics',
 'Film(s)',
 'Screen story by',
 'Hangul',
 'Revised Romanization',
 'McCune–Reischauer',
 'Developer(s)',
 'Publisher(s)',
 'Designer(s)',
 'Programmer(s)',
 'Artist(s)',
 'Writer(s)',
 'Engine',
 'Platform(s)',
 'Release',
 'Mode(s)',
 'Original work',
 'Television series',
 'Japanese',
 'Hepburn',
 'Literally',
 'Cantonese',
 'Full name',
 'Height',
 'Seasons',
 'Chinese',
 'Other names',
 'Relatives',
 'Yiddish',
 'Formerly',
 'Key people',
 'Total assets',
 'Owner',
 'Number of employees',
 'Divisions',
 'Subsidiaries',
 'Arabic',
 'Romanized',
 'Predecessor',
 'Founders',
 'Area served',
 'Products',
 'Services',
 'Russian',
 'Hebrew',
 'Revenue',
 'Operating income',
 'Polish']

In [22]:
wiki_movies = [movie for movie in wiki_movies_raw
               if ('Director' in movie or 'Directed by' in movie)
                   and 'imdb_link' in movie]
len(wiki_movies)

7080

In [25]:
wiki_movies = [movie for movie in wiki_movies_raw
               if ('Director' in movie or 'Directed by' in movie)
                   and 'imdb_link' in movie
                   and 'No. of episodes' not in movie]
len(wiki_movies)

7076

In [26]:
wiki_movies_df[wiki_movies_df['Arabic'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
7060,https://en.wikipedia.org/wiki/The_Insult_(film),2018.0,https://www.imdb.com/title/tt7048622/,The Insult,Ziad Doueiri,"[Rachid Bouchareb, Jean Bréhat, Julie Gayet, A...",NaN,NaN,NaN,"[Adel Karam, Kamel El Basha]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7293,https://en.wikipedia.org/wiki/Capernaum_(film),2018.0,https://www.imdb.com/title/tt8267604/,Capernaum,Nadine Labaki,"[Michel Merkt, Khaled Mouzanar]","[Nadine Labaki, Jihad Hojaily, Michelle Keserw...","[Georges Khabbaz, Nadine Labaki, Michelle Kese...",NaN,"[Zain Al Rafeea, Yordanos Shiferaw, Boluwatife...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
def clean_movie(movie):
    movie = dict(movie) #create a non-destructive copy
    return movie

In [30]:
wiki_movies_df[wiki_movies_df['Arabic'].notnull()]['url']

7060    https://en.wikipedia.org/wiki/The_Insult_(film)
7293     https://en.wikipedia.org/wiki/Capernaum_(film)
Name: url, dtype: object

In [31]:
sorted(wiki_movies_df.columns.tolist())

['Actor control',
 'Adaptation by',
 'Alias',
 'Alma mater',
 'Also known as',
 'Animation by',
 'Arabic',
 'Area',
 'Area served',
 'Artist(s)',
 'Attraction type',
 'Audio format',
 'Author',
 'Based on',
 'Biographical data',
 'Bopomofo',
 'Born',
 'Box office',
 'Budget',
 'Camera setup',
 'Cantonese',
 'Characters',
 'Children',
 'Chinese',
 'Cinematography',
 'Closing date',
 'Color process',
 'Comics',
 'Composer(s)',
 'Coordinates',
 'Country',
 'Country of origin',
 'Cover artist',
 'Created by',
 'Date premiered',
 'Designer(s)',
 'Developed by',
 'Developer(s)',
 'Dewey Decimal',
 'Died',
 'Directed by',
 'Director',
 'Distributed by',
 'Distributor',
 'Divisions',
 'Duration',
 'Edited by',
 'Editor(s)',
 'Ending theme',
 'Engine',
 'Engine(s)',
 'Executive producer(s)',
 'Family',
 'Fate',
 'Film(s)',
 'Followed by',
 'Format(s)',
 'Formerly',
 'Founded',
 'Founder',
 'Founders',
 'French',
 'Full name',
 'Gender',
 'Genre',
 'Genre(s)',
 'Genres',
 'Gwoyeu Romatzyh',
 'Hangul',
 'Hanyu Pinyin',
 'Headquarters',
 'Hebrew',
 'Height',
 'Hepburn',
 'Hokkien POJ',
 'IPA',
 'ISBN',
 'Illustrator',
 'Industry',
 'Instruments',
 'Japanese',
 'Jyutping',
 'Key people',
 'LC Class',
 'Label',
 'Labels',
 'Language',
 'Length',
 'Literal meaning',
 'Literally',
 'Mandarin',
 'McCune–Reischauer',
 'Media type',
 'Mode(s)',
 'Music',
 'Music by',
 'Name',
 'Narrated by',
 'Nationality',
 'No. of episodes',
 'No. of seasons',
 'Novel(s)',
 'Number of employees',
 'OCLC',
 'Occupation',
 'Opening date',
 'Opening theme',
 'Operating income',
 'Original language',
 'Original language(s)',
 'Original network',
 'Original release',
 'Original title',
 'Original work',
 'Other names',
 'Owner',
 'Pages',
 'Parent',
 'Parent(s)',
 'Picture format',
 'Place premiered',
 'Platform(s)',
 'Polish',
 'Portrayed by',
 'Preceded by',
 'Predecessor',
 'Produced by',
 'Producer',
 'Producer(s)',
 'Production company',
 'Production company(s)',
 'Production location(s)',
 'Productioncompanies ',
 'Productioncompany ',
 'Products',
 'Programmer(s)',
 'Publication date',
 'Published',
 'Published in English',
 'Publisher',
 'Publisher(s)',
 'Recorded',
 'Relatives',
 'Release',
 'Release date',
 'Release(s)',
 'Released',
 'Replaced',
 'Replaced by',
 'Resting place',
 'Revenue',
 'Revised Romanization',
 'Romanized',
 'Running time',
 'Russian',
 'Screen story by',
 'Screenplay by',
 'Seasons',
 'Series',
 'Services',
 'Set in',
 'Setting',
 'Simplified',
 'Simplified Chinese',
 'Species',
 'Spouse(s)',
 'Starring',
 'Status',
 'Story by',
 'Subject',
 'Subsidiaries',
 'Suggested by',
 'Television series',
 'Text',
 'Theme music composer',
 'Total assets',
 'Traditional',
 'Traditional Chinese',
 'Transcriptions',
 'Type',
 'Venue',
 'Voices of',
 'Wade–Giles',
 'Website',
 'Writer(s)',
 'Written by',
 'Yale Romanization',
 'Years active',
 'Yiddish',
 'imdb_link',
 'title',
 'url',
 'year']

In [38]:
wiki_movies_df[wiki_movies_df['Arabic'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
7060,https://en.wikipedia.org/wiki/The_Insult_(film),2018.0,https://www.imdb.com/title/tt7048622/,The Insult,Ziad Doueiri,"[Rachid Bouchareb, Jean Bréhat, Julie Gayet, A...",NaN,NaN,NaN,"[Adel Karam, Kamel El Basha]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7293,https://en.wikipedia.org/wiki/Capernaum_(film),2018.0,https://www.imdb.com/title/tt8267604/,Capernaum,Nadine Labaki,"[Michel Merkt, Khaled Mouzanar]","[Nadine Labaki, Jihad Hojaily, Michelle Keserw...","[Georges Khabbaz, Nadine Labaki, Michelle Kese...",NaN,"[Zain Al Rafeea, Yordanos Shiferaw, Boluwatife...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
wiki_movies_df[wiki_movies_df['Cantonese'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
6674,https://en.wikipedia.org/wiki/Ip_Man_3,2016.0,https://www.imdb.com/title/tt2888046/,Ip Man 3,Wilson Yip,Raymond Wong,NaN,NaN,NaN,"[Donnie Yen, Zhang Jin, Lynn Hung, Patrick Tam...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
wiki_movies_df[wiki_movies_df['Chinese'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
6841,https://en.wikipedia.org/wiki/Rock_Dog,2017.0,https://www.imdb.com/title/tt2822672/,Rock Dog,Ash Brannon,"[Amber Wang, David B. Miller, Rob Feng, Joyce ...","[Ash Brannon, Kurt Voelker]","[Ash Brannon, Zheng Jun]","[Tibetan Rock Dog, by Zheng Jun]","[Luke Wilson, Eddie Izzard, J. K. Simmons, Lew...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
wiki_movies_df[wiki_movies_df['French'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
1976,https://en.wikipedia.org/wiki/The_Fifth_Element,1997.0,https://www.imdb.com/title/tt0119116/,The Fifth Element,Luc Besson,Patrice Ledoux,"[Luc Besson, Robert Mark Kamen]",Luc Besson,NaN,"[Bruce Willis, Gary Oldman, Ian Holm, Chris Tu...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
wiki_movies_df[wiki_movies_df['Hangul'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
3548,https://en.wikipedia.org/wiki/Wonderful_Days_(...,2003.0,https://www.imdb.com/title/tt0353014/,Wonderful Days,Kim Moon-saeng,"[Hwang K. S., Kyeong Hag Lee]",NaN,NaN,NaN,"[Korean, Ji Hoon Choi, Yeong Seon Eun, In Seon...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4403,https://en.wikipedia.org/wiki/Shark_Bait,2006.0,https://www.imdb.com/title/tt0820142/,Shark Bait (AKA: The Reef: Shark Bait),"[Howard E. Baker, John Fox]",NaN,NaN,NaN,NaN,"[Freddie Prinze, Jr., Evan Rachel Wood, Donal ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
wiki_movies_df[wiki_movies_df['Hebrew'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
7089,https://en.wikipedia.org/wiki/Foxtrot_(2017_film),2018.0,https://www.imdb.com/title/tt6896536/,Foxtrot,Samuel Maoz,"[Eitan Mansuri, [, he, ]]",NaN,NaN,NaN,"[Lior Ashkenazi, Sarah Adler]",...,NaN,NaN,NaN,NaN,NaN,NaN,פוֹקְסטְרוֹט,NaN,NaN,NaN

In [54]:
wiki_movies_df[wiki_movies_df['Japanese'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
6611,https://en.wikipedia.org/wiki/When_Marnie_Was_...,2015.0,https://www.imdb.com/title/tt3398268/,When Marnie Was There,Hiromasa Yonebayashi,Yoshiaki Nishimura,"[Masashi Andō, Keiko Niwa, Hiromasa Yonebayashi]",NaN,"[When Marnie Was There, by, Joan G. Robinson]","[Sara Takatsuki, Kasumi Arimura]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7055,https://en.wikipedia.org/wiki/Mary_and_the_Wit...,2018.0,https://www.imdb.com/title/tt6336356/,Mary and The Witch's Flower,Hiromasa Yonebayashi,Yoshiaki Nishimura,"[Riko Sakaguchi, Hiromasa Yonebayashi]",NaN,"[The Little Broomstick, by, Mary Stewart, [1]]","[Hana Sugisaki, Yūki Amami, Fumiyo Kohinata]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7242,https://en.wikipedia.org/wiki/My_Hero_Academia...,2018.0,https://www.imdb.com/title/tt7745068/,My Hero Academia: Two Heroes,Kenji Nagasaki,"[Yoshihiro Oyabu, Koji Nagai, Wakana Okamura, ...",NaN,NaN,"[My Hero Academia, by, Kōhei Horikoshi]",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7289,https://en.wikipedia.org/wiki/Shoplifters,2018.0,https://www.imdb.com/title/tt8075192/,Shoplifters,Hirokazu Kore-eda,"[Matsuzaki Kaoru, Yose Akihiko, Taguchi Hijiri]",NaN,NaN,NaN,"[Lily Franky, Sakura Ando, Mayu Matsuoka, Kair...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
wiki_movies_df[wiki_movies_df['Literally'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
6611,https://en.wikipedia.org/wiki/When_Marnie_Was_...,2015.0,https://www.imdb.com/title/tt3398268/,When Marnie Was There,Hiromasa Yonebayashi,Yoshiaki Nishimura,"[Masashi Andō, Keiko Niwa, Hiromasa Yonebayashi]",NaN,"[When Marnie Was There, by, Joan G. Robinson]","[Sara Takatsuki, Kasumi Arimura]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7060,https://en.wikipedia.org/wiki/The_Insult_(film),2018.0,https://www.imdb.com/title/tt7048622/,The Insult,Ziad Doueiri,"[Rachid Bouchareb, Jean Bréhat, Julie Gayet, A...",NaN,NaN,NaN,"[Adel Karam, Kamel El Basha]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7289,https://en.wikipedia.org/wiki/Shoplifters,2018.0,https://www.imdb.com/title/tt8075192/,Shoplifters,Hirokazu Kore-eda,"[Matsuzaki Kaoru, Yose Akihiko, Taguchi Hijiri]",NaN,NaN,NaN,"[Lily Franky, Sakura Ando, Mayu Matsuoka, Kair...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
wiki_movies_df[wiki_movies_df['Mandarin'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
887,https://en.wikipedia.org/wiki/The_Wedding_Banquet,1993.0,https://www.imdb.com/title/tt0107156/,The Wedding Banquet,Ang Lee,"[Ang Lee, Ted Hope, James Schamus]",NaN,NaN,NaN,"[Ah-Leh Gua, Sihung Lung, May Chin, Winston Ch...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1598,"https://en.wikipedia.org/wiki/East_Palace,_Wes...",1996.0,https://www.imdb.com/title/tt0119007/,"East Palace, West Palace",Zhang Yuan,"[Christophe Jung, Christophe Ménager, Zhang Yu...",NaN,NaN,NaN,"[Si Han, Hu Jun, Zhao Wei]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6674,https://en.wikipedia.org/wiki/Ip_Man_3,2016.0,https://www.imdb.com/title/tt2888046/,Ip Man 3,Wilson Yip,Raymond Wong,NaN,NaN,NaN,"[Donnie Yen, Zhang Jin, Lynn Hung, Patrick Tam...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6834,https://en.wikipedia.org/wiki/The_Great_Wall_(...,2017.0,https://www.imdb.com/title/tt2034800/,The Great Wall,Zhang Yimou,"[Thomas Tull, Charles Roven, Jon Jashni, Peter...","[Carlo Bernard, Doug Miro, Tony Gilroy]","[Max Brooks, Edward Zwick, Marshall Herskovitz]",NaN,"[Matt Damon, Jing Tian, Pedro Pascal, Willem D...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
wiki_movies_df[wiki_movies_df['McCune–Reischauer'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
3548,https://en.wikipedia.org/wiki/Wonderful_Days_(...,2003.0,https://www.imdb.com/title/tt0353014/,Wonderful Days,Kim Moon-saeng,"[Hwang K. S., Kyeong Hag Lee]",NaN,NaN,NaN,"[Korean, Ji Hoon Choi, Yeong Seon Eun, In Seon...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4403,https://en.wikipedia.org/wiki/Shark_Bait,2006.0,https://www.imdb.com/title/tt0820142/,Shark Bait (AKA: The Reef: Shark Bait),"[Howard E. Baker, John Fox]",NaN,NaN,NaN,NaN,"[Freddie Prinze, Jr., Evan Rachel Wood, Donal ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
wiki_movies_df[wiki_movies_df['Original title'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
1942,https://en.wikipedia.org/wiki/Crayola_Kids_Adv...,1997.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4976,https://en.wikipedia.org/wiki/Waltz_with_Bashir,2008.0,https://www.imdb.com/title/tt1185616/,Waltz with Bashir,Ari Folman,"[Ari Folman, Serge Lalou, Gerhard Meixner, Yae...",NaN,NaN,NaN,Ari Folman,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
wiki_movies_df[wiki_movies_df['Polish'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
7305,https://en.wikipedia.org/wiki/Cold_War_(2018_f...,2018.0,https://www.imdb.com/title/tt6543652/,Cold War,Paweł Pawlikowski,"[Tanya Seghatchian, Ewa Puszczyńska]",NaN,NaN,NaN,"[Joanna Kulig, Tomasz Kot, Borys Szyc, Agata K...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimna wojna

In [60]:
wiki_movies_df[wiki_movies_df['Revised Romanization'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
3548,https://en.wikipedia.org/wiki/Wonderful_Days_(...,2003.0,https://www.imdb.com/title/tt0353014/,Wonderful Days,Kim Moon-saeng,"[Hwang K. S., Kyeong Hag Lee]",NaN,NaN,NaN,"[Korean, Ji Hoon Choi, Yeong Seon Eun, In Seon...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4403,https://en.wikipedia.org/wiki/Shark_Bait,2006.0,https://www.imdb.com/title/tt0820142/,Shark Bait (AKA: The Reef: Shark Bait),"[Howard E. Baker, John Fox]",NaN,NaN,NaN,NaN,"[Freddie Prinze, Jr., Evan Rachel Wood, Donal ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
wiki_movies_df[wiki_movies_df['Romanized'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
7060,https://en.wikipedia.org/wiki/The_Insult_(film),2018.0,https://www.imdb.com/title/tt7048622/,The Insult,Ziad Doueiri,"[Rachid Bouchareb, Jean Bréhat, Julie Gayet, A...",NaN,NaN,NaN,"[Adel Karam, Kamel El Basha]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7076,https://en.wikipedia.org/wiki/Loveless_(film),2018.0,https://www.imdb.com/title/tt6304162/,Loveless,Andrey Zvyagintsev,"[Alexander Rodnyansky, Sergey Melkumov, Gleb F...","[Oleg Negin, Andrey Zvyagintsev]",NaN,NaN,"[Maryana Spivak, Aleksey Rozin, Matvey Novikov...",...,NaN,NaN,NaN,NaN,NaN,Нелюбовь,NaN,NaN,NaN,NaN

In [62]:
wiki_movies_df[wiki_movies_df['Russian'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
7076,https://en.wikipedia.org/wiki/Loveless_(film),2018.0,https://www.imdb.com/title/tt6304162/,Loveless,Andrey Zvyagintsev,"[Alexander Rodnyansky, Sergey Melkumov, Gleb F...","[Oleg Negin, Andrey Zvyagintsev]",NaN,NaN,"[Maryana Spivak, Aleksey Rozin, Matvey Novikov...",...,NaN,NaN,NaN,NaN,NaN,Нелюбовь,NaN,NaN,NaN,NaN

In [63]:
wiki_movies_df[wiki_movies_df['Simplified'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
1598,"https://en.wikipedia.org/wiki/East_Palace,_Wes...",1996.0,https://www.imdb.com/title/tt0119007/,"East Palace, West Palace",Zhang Yuan,"[Christophe Jung, Christophe Ménager, Zhang Yu...",NaN,NaN,NaN,"[Si Han, Hu Jun, Zhao Wei]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6674,https://en.wikipedia.org/wiki/Ip_Man_3,2016.0,https://www.imdb.com/title/tt2888046/,Ip Man 3,Wilson Yip,Raymond Wong,NaN,NaN,NaN,"[Donnie Yen, Zhang Jin, Lynn Hung, Patrick Tam...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6834,https://en.wikipedia.org/wiki/The_Great_Wall_(...,2017.0,https://www.imdb.com/title/tt2034800/,The Great Wall,Zhang Yimou,"[Thomas Tull, Charles Roven, Jon Jashni, Peter...","[Carlo Bernard, Doug Miro, Tony Gilroy]","[Max Brooks, Edward Zwick, Marshall Herskovitz]",NaN,"[Matt Damon, Jing Tian, Pedro Pascal, Willem D...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6885,https://en.wikipedia.org/wiki/Born_in_China,2017.0,https://www.imdb.com/title/tt4629266/,Born in China,Lu Chuan,"[Roy Conli, Brian Leith, Phil Chapman]","[David Fowler, Brian Leith, Phil Chapman, Lu C...",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
wiki_movies_df[wiki_movies_df['Traditional'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
887,https://en.wikipedia.org/wiki/The_Wedding_Banquet,1993.0,https://www.imdb.com/title/tt0107156/,The Wedding Banquet,Ang Lee,"[Ang Lee, Ted Hope, James Schamus]",NaN,NaN,NaN,"[Ah-Leh Gua, Sihung Lung, May Chin, Winston Ch...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1598,"https://en.wikipedia.org/wiki/East_Palace,_Wes...",1996.0,https://www.imdb.com/title/tt0119007/,"East Palace, West Palace",Zhang Yuan,"[Christophe Jung, Christophe Ménager, Zhang Yu...",NaN,NaN,NaN,"[Si Han, Hu Jun, Zhao Wei]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6674,https://en.wikipedia.org/wiki/Ip_Man_3,2016.0,https://www.imdb.com/title/tt2888046/,Ip Man 3,Wilson Yip,Raymond Wong,NaN,NaN,NaN,"[Donnie Yen, Zhang Jin, Lynn Hung, Patrick Tam...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6834,https://en.wikipedia.org/wiki/The_Great_Wall_(...,2017.0,https://www.imdb.com/title/tt2034800/,The Great Wall,Zhang Yimou,"[Thomas Tull, Charles Roven, Jon Jashni, Peter...","[Carlo Bernard, Doug Miro, Tony Gilroy]","[Max Brooks, Edward Zwick, Marshall Herskovitz]",NaN,"[Matt Damon, Jing Tian, Pedro Pascal, Willem D...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6885,https://en.wikipedia.org/wiki/Born_in_China,2017.0,https://www.imdb.com/title/tt4629266/,Born in China,Lu Chuan,"[Roy Conli, Brian Leith, Phil Chapman]","[David Fowler, Brian Leith, Phil Chapman, Lu C...",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
wiki_movies_df[wiki_movies_df['Yiddish'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
6944,https://en.wikipedia.org/wiki/Menashe_(film),2017.0,https://www.imdb.com/title/tt6333086/,Menashe,"[Joshua Z. Weinstein, [, yi, ]]","[Alex Lipschultz, Traci Carlson, Joshua Z. Wei...",NaN,NaN,NaN,"[Menashe Lustig, [, yi, ], Ruben Niborski, Yoe...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
def clean_movie(movie):
    movie = dict(movie) #create a non-destructive copy
    alt_titles = {}
    for key in ['Also known as','Arabic','Cantonese','Chinese','French',
                'Hangul','Hebrew','Hepburn','Japanese','Literally',
                'Mandarin','McCune–Reischauer','Original title','Polish',
                'Revised Romanization','Romanized','Russian',
                'Simplified','Traditional','Yiddish']:
        if key in movie:
            alt_titles[key] = movie[key]
            movie.pop(key)
    if len(alt_titles) > 0:
        movie['alt_titles'] = alt_titles

    return movie

In [68]:
clean_movies = [clean_movie(movie) for movie in wiki_movies]

In [69]:
wiki_movies_df = pd.DataFrame(clean_movies)
sorted(wiki_movies_df.columns.tolist())

['Adaptation by',
 'Animation by',
 'Audio format',
 'Based on',
 'Box office',
 'Budget',
 'Cinematography',
 'Color process',
 'Composer(s)',
 'Country',
 'Country of origin',
 'Created by',
 'Directed by',
 'Director',
 'Distributed by',
 'Distributor',
 'Edited by',
 'Editor(s)',
 'Executive producer(s)',
 'Followed by',
 'Genre',
 'Label',
 'Language',
 'Length',
 'Music by',
 'Narrated by',
 'Original language(s)',
 'Original network',
 'Original release',
 'Picture format',
 'Preceded by',
 'Produced by',
 'Producer',
 'Producer(s)',
 'Production company(s)',
 'Production location(s)',
 'Productioncompanies ',
 'Productioncompany ',
 'Recorded',
 'Release date',
 'Released',
 'Running time',
 'Screen story by',
 'Screenplay by',
 'Starring',
 'Story by',
 'Suggested by',
 'Theme music composer',
 'Venue',
 'Voices of',
 'Written by',
 'alt_titles',
 'imdb_link',
 'title',
 'url',
 'year']